info:
  component: Liberty Config Server
server:
  port: 8888
management:
  context_path: /admin  
spring:
  application:
    name: liberty-api-config-server
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/spring-cloud-samples/config-repo
          uri: file://C:\\workspace\\projects\\config-repo
          #basedir: target/config